### PR TITLE
Open layers map

### PR DESCRIPTION
**Pull request by oftfrfbf**
The file "indexUpdated.html" is the one that I demo'd on Friday, and so it reflects the most updated version of the front page. There are some other "*.html" files that don't need to be integrated.

### CODE REVIEW

**Comment by mira67** [comment]
So the black hole hasn't been fixed yet, right? But the lat/lon box selection works, right?

**Comment by oftfrfbf** [comment]
Those two problems go hand in hand in that updating the map will change the projection and will require the lat/lon to work differently. I'm still working on fixing that...

**Comment by mira67** [comment]
I see, let take a look at the problem together after the meeting if still not fixed.
And discuss how to start to improve the results page design. Hold on this merge to wait for the map and user configuration fixed.

**Comment by mira67** [comment]
#18 Merged
For the query split idea we discussed today, re-discussed with Chao, since 10 images loading maybe very fast, so let's only implement the user driven ajax query, meaning that: every time user slide through the time to view new image, we check if already loaded, if yes, display; if no, make a small query. This should be easy to make work.

**Pull request merged**
